### ISSUE TITLE
TypeError: Wrong number or type of arguments

### ISSUE THREAD

**Issue by sunjaxx** [paulgb/penkit#5]
I am on win 10, and I'm getting:

```
TypeError: Wrong number or type of arguments for overloaded function 'new_RoutingModel'.
  Possible C/C++ prototypes are:
    operations_research::RoutingModel::RoutingModel(operations_research::RoutingIndexManager const &)
    operations_research::RoutingModel::RoutingModel(operations_research::RoutingIndexManager const &,operations_research::RoutingModelParameters const &)
```

Any suggestions?
Thanks

**Comment by javogel** [comment]
I'm on mac and getting this same error. I installed `penkit-optimize` for python3 and `spatialindex` using brew. Any advice on how to troubleshoot this?

**Comment by lr1729** [comment]
This is fixed in #4

**Comment by paulgb** [comment]
Thanks for reporting and sorry for the slow reply, it took a while to find the time to set up an environment and replicate. I've fixed the issue and if you run `pip install -U penkit-optimize` it should solve them, if not let me know and I'll be more responsive this time.

**Comment by paulgb** [comment]
(Actually, credit where it's due, @lr1729 fixed the issue; I just merged it)
